[_]
schema-version = "0.2"

[[io.buildpacks.group]]
  id = "renku/conda-nodefaults"
  optional = true
[[io.buildpacks.group]]
  id = "paketo-buildpacks/python"
[[io.buildpacks.group]]
  id = "renku/python-dependency-manager"
[[io.buildpacks.group]]
  id = "renku/renku-variables"
[[io.buildpacks.group]]
  id = "renku/vscodium"
[[io.buildpacks.group]]
  id = "heroku/deb-packages"
  optional = true
[[io.buildpacks.group]]
  id = "renku/init-scripts"
  optional = true
[[io.buildpacks.group]]
  id = "paketo-buildpacks/procfile"

[[io.buildpacks.build.env]]
name = "BP_PROCFILE_DEFAULT_PROCESS"
value = "streamlit"
